Add and rearrange a few fcntl pieces
rust-lang/libc pull request #1756
Opened 2020-05-10 05:02 UTC by khuey

Add f_owner_ex, F_GET/SETOWN_EX, F_GET/SETSIG, and move F_OWNER_* to the toplevel linux-like module because they're libc and platform agnostic.

2020-05-10 05:02 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @JohnTitor (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2020-10-06 23:50 UTC, joshtriplett commented
Closing and reopening to re-run CI.

2020-10-15 20:37 UTC, JohnTitor requested changes
The definition itself looks good to me but we need to tweak the test to pass CI.

2020-10-15 20:37 UTC, JohnTitor commented on src/unix/linux_like/linux/mod.rs
> +        pub type_: ::c_int,
We should add `f_owner_ex` here:

https://github.com/rust-lang/libc/blob/0d374002b8d4972e97e04b0a7fb1a210e22368ed/libc-test/build.rs#L2513-L2522

2021-03-16 00:45 UTC, khuey commented
I'm still not sure how to get this test to pass unfortunately. There appears to be something going wrong inside ctest, perhaps?

@JohnTitor

2021-11-05 01:53 UTC, JohnTitor commented
I'm going to close as inactive, feel free to rebase and re-open when you get some time :)

2021-11-05 01:53 UTC, closed without merging