openbsd update deprecate few constants
rust-lang/libc pull request #2190
Opened 2021-05-22 07:35 UTC by devnexen

2021-05-22 07:35 UTC, rust-highfive commented
r? @Amanieu

(rust-highfive has picked a reviewer for you, use r? to override)

2021-05-22 07:40 UTC, JohnTitor requested changes
There're some typos found by @semarie.

2021-05-22 07:40 UTC, JohnTitor commented on src/unix/bsd/netbsdlike/openbsd/mod.rs
> +    note = "Possibily increasing over the releases and might not be so used in the field")]
```suggestion
    note = "Possibly increasing over the releases and might not be so used in the field")]
```

2021-05-22 07:40 UTC, JohnTitor commented on src/unix/bsd/netbsdlike/openbsd/mod.rs
> +    note = "Possibily increasing over the releases and might not be so used in the field")]
```suggestion
    note = "Possibly increasing over the releases and might not be so used in the field")]
```

2021-05-22 07:46 UTC, semarie commented
with typo changes, LGTM

2021-05-23 08:22 UTC, JohnTitor approved these changes

2021-05-23 08:22 UTC, JohnTitor commented
r? @JohnTitor @bors r+

2021-05-23 14:20 UTC, merged