pthread_spinlock api remaining bsd systems
rust-lang/libc pull request #2246
Opened 2021-06-16 18:35 UTC by devnexen

2021-06-16 18:35 UTC, rust-highfive commented
Some changes occurred in OpenBSD module

cc @semarie

2021-06-16 18:35 UTC, rust-highfive commented
r? @JohnTitor

(rust-highfive has picked a reviewer for you, use r? to override)

2021-06-17 04:45 UTC, semarie requested changes

2021-06-17 04:45 UTC, semarie commented on src/unix/bsd/netbsdlike/openbsd/mod.rs
> +    pub struct __c_anonymous_pthread_spinlock {
`pthread_spinlock` struct is internal and isn't in public header on purpose. the visible part is only a pointer, nothing else.

it is the same kind of type as `pthread_t` which is defined as `pub type pthread_t = ::uintptr_t` in Rust.

2021-06-17 04:45 UTC, semarie commented on src/unix/bsd/netbsdlike/openbsd/mod.rs
> +    pub fn pthread_spin_init(lock: *mut pthread_spinlock_t, pshared: ::c_int) -> ::c_int;
if I don't mess myself, pthread_spin_ functions could be commun with at least NetBSD.

2021-06-17 06:29 UTC, semarie requested changes

2021-06-17 06:29 UTC, semarie commented on src/unix/bsd/freebsdlike/dragonfly/mod.rs
> +    pub struct __c_anonymous_pthread_spinlock_s {
it isn't exactly my area but I think if the OS define a struct as opaque, it should be kept opaque.

`pthread_spinlock_t` is opaque in DragonflyBSD too: [sys/sys/_pthreadtypes.h](https://github.com/DragonFlyBSD/DragonFlyBSD/blob/c163a4d7ee9c6857ee4e04a3a2cbb50c3de29da1/sys/sys/_pthreadtypes.h)

2021-06-17 06:29 UTC, semarie commented on libc-test/build.rs
> +        "machine/spinlock.h",
this definition shouldn't be need now that you don't use `_atomic_lock_t` type.

the tests passes on OpenBSD without it.

2021-06-17 06:41 UTC, semarie commented
it mess to me you reintroduced `__c_anonymous_pthread_spinlock` on OpenBSD while removing it from DragonflyBSD...

2021-06-17 06:52 UTC, devnexen commented
ah yes wrong rebasing

2021-06-17 08:38 UTC, semarie commented
rebasing still a bit wrong :
- `if ty.starts_with("__c_anonymous_") {` isn't need anymore in `test_openbsd()` function
- pthread_spin_ functions could be merged with NetBSD inside `src/unix/bsd/netbsdlike/mod.rs`

2021-06-17 08:44 UTC, devnexen commented
true. Merci beaucoup for your review ;-)

2021-06-17 09:14 UTC, semarie approved these changes
fine with me. thanks

2021-06-18 15:15 UTC, JohnTitor approved these changes

2021-06-18 15:15 UTC, JohnTitor commented
Thanks! @bors r+

2021-06-18 17:05 UTC, merged