openbsd adding kinfo_vmentry
rust-lang/libc pull request #2302
Opened 2021-07-25 14:31 UTC by devnexen

2021-07-25 14:31 UTC, rust-highfive commented
Some changes occurred in OpenBSD module

cc @semarie

2021-07-25 14:31 UTC, rust-highfive commented
r? @JohnTitor

(rust-highfive has picked a reviewer for you, use r? to override)

2021-07-25 14:56 UTC, semarie requested changes
just tested (with `kve_flags` changed) and it is fine.

2021-07-25 14:56 UTC, semarie commented on src/unix/bsd/netbsdlike/openbsd/mod.rs
> +        kve_flags: u8,
maybe adding `pub` to `kve_flags` too ?

2021-07-25 16:55 UTC, semarie approved these changes
fine with me

2021-07-27 18:41 UTC, JohnTitor approved these changes

2021-07-27 18:41 UTC, JohnTitor commented
@bors r+

2021-07-27 20:43 UTC, merged