Document stat.st_blksize changes on DragonFly BSD
rust-lang/libc pull request #2487
Opened 2021-10-30 03:55 UTC by rtzoeller

The tests are currently failing on DragonFly BSD, due to [changes to `stat.st_blksize`](https://github.com/DragonFlyBSD/DragonFlyBSD/commit/34c6728ee290889398ff2f1305a91f08aa6b0b35) among other reasons.

`st_blksize` is now an `i64`, and has moved to take up a previously reserved struct member.

2021-10-30 03:55 UTC, rust-highfive commented
r? @Amanieu

(rust-highfive has picked a reviewer for you, use r? to override)

2021-10-30 19:53 UTC, Amanieu commented
What is the long-term solution for this? I don't see how the deprecation warning is helpful since there is no action anyone can do in their code to resolve it.

2021-10-30 19:57 UTC, rtzoeller commented
@Amanieu in a future release, we should update the struct definition to match DragonFly's. This is just an announcement of that future breaking change. 

My understanding was that this was the correct course of action, per the breaking change policy and previous conversations with @JohnTitor.

If we should handle this differently, let me know and I can update the PR.

2021-10-30 20:00 UTC, Amanieu commented
I will let @JohnTitor review this since you have previously discussed it with him.

r? @JohnTitor

2021-11-02 17:59 UTC, JohnTitor requested changes
Yeah, let's deprecate first so that users can notice the change and prepare their own struct if they want to use an older one.
Left some comments about version and note.

2021-11-02 17:59 UTC, JohnTitor commented on src/unix/bsd/freebsdlike/dragonfly/mod.rs
> +        note = "stat.st_blksize is an i64 and replaces stat.st_qspare1 in DragonFly 5.8"
I think something like this is clearer:

```suggestion
        note = "stat.st_blksize is an i64 and stat.st_qspare1 is replaced with stat.st_blksize in DragonFly 5.8"
```

2021-11-02 17:59 UTC, JohnTitor commented on src/unix/bsd/freebsdlike/dragonfly/mod.rs
> +        since = "0.2.106",
```suggestion
        since = "0.2.107",
```

2021-11-02 20:49 UTC, JohnTitor commented
Thanks! @bors r+

2021-11-03 08:30 UTC, JohnTitor commented
CI should be fixed now, @bors retry

2021-11-03 09:38 UTC, JohnTitor commented
Some functions need `#[allow(deprecated)]`.

2021-11-06 03:30 UTC, rtzoeller commented
@JohnTitor fixed! For some reason I couldn't see the actual error in the log on GitHub, and had to download it and view it locally.

2021-11-06 09:17 UTC, JohnTitor commented
> For some reason I couldn't see the actual error in the log on GitHub, and had to download it and view it locally.

Hm, it's displayed fine on my env, maybe loading the log failed at that time?

Anyway, the build should be fixed, @bors r+

2021-11-06 10:22 UTC, merged