Add OpenBSD kinfo_proc struct
rust-lang/libc pull request #2786
Opened 2022-05-10 16:04 UTC by Freaky

2022-05-10 16:58 UTC, semarie requested changes
there is typo in field

2022-05-10 16:58 UTC, semarie commented on src/unix/bsd/netbsdlike/openbsd/mod.rs
> +        pub ip_uvalid: i64,
wrong name : `p_uvalid`

2022-05-10 17:02 UTC, Freaky commented on src/unix/bsd/netbsdlike/openbsd/mod.rs
> +        pub ip_uvalid: i64,
Good catch!

2022-05-10 17:31 UTC, semarie approved these changes
tests passed, LGTM.
thanks

2022-05-11 01:02 UTC, Amanieu commented
@bors r+

2022-05-11 02:04 UTC, merged