fcntl F_DUPFD_CLOEXEC has different values on Solaris and Illumos
rust-lang/libc pull request #2900
Opened 2022-09-05 20:51 UTC by gco

2022-09-05 20:51 UTC, rust-highfive commented
Some changes occurred in solarish module

cc @jclulow,@pfmooney

2022-09-05 20:51 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @Amanieu (or someone else) soon.

Please see [the contribution instructions](https://github.com/rust-lang/libc/blob/master/CONTRIBUTING.md) for more information.

2022-09-05 21:03 UTC, jclulow requested changes

2022-09-05 21:03 UTC, jclulow commented on src/unix/solarish/illumos.rs
> +// fcntl F_DUPFD_CLOEXEC has different values on Solaris and Illumos
```suggestion
```

I would remove the comments.  The separate file structure already denotes different constants for illumos and Solaris, and the file would be full of comments like this if we noted every difference.

2022-09-05 21:03 UTC, jclulow commented on src/unix/solarish/solaris.rs
> +// fcntl F_DUPFD_CLOEXEC has different values on Solaris and Illumos
```suggestion
```

2022-09-05 21:18 UTC, jclulow approved these changes
Looks good to me -- thanks!

2022-09-10 22:49 UTC, JohnTitor approved these changes

2022-09-10 22:49 UTC, JohnTitor commented
@bors r+

2022-09-11 00:53 UTC, merged