Add `MSG_WAITFORONE` to freebsd, openbsd, and illumos
rust-lang/libc pull request #3224
Opened 2023-04-25 19:39 UTC by stevenengler

Adds `MSG_WAITFORONE` to freebsd, openbsd, and illumos, as requested in https://github.com/nix-rust/nix/pull/2014.

I got the values from:

- freebsd: http://fxr.watson.org/fxr/source/sys/socket.h#L473
- openbsd: https://github.com/openbsd/src/blob/2852e11abfc574a216ce741308fb0c6968d9617a/sys/sys/socket.h#L512
- illumos: https://github.com/TritonDataCenter/illumos-joyent/blob/ead9b236523b9f846f65f0dcb2e2157878a97daa/usr/src/boot/sys/sys/socket.h#L434

This flag is also supposedly supported on [solaris](https://docs.oracle.com/cd/E88353_01/html/E37843/recvmmsg-3c.html), but I don't know how to find the value. If anyone knows what it is, I'll add it to the PR.

2023-04-25 19:43 UTC, pfmooney requested changes
As noted, this constant should not be defined for illumos.

2023-04-25 19:44 UTC, stevenengler commented on src/unix/solarish/illumos.rs
> +pub const MSG_WAITFORONE: ::c_int = 0x80000;
Okay I'll remove it. Thanks!

2023-04-26 04:46 UTC, semarie approved these changes
LGTM for openbsd part. thanks.

2023-04-26 10:29 UTC, JohnTitor approved these changes

2023-04-26 10:29 UTC, JohnTitor commented
Thanks for the PR and reviewing! @bors r+

2023-04-28 17:22 UTC, stevenengler commented
Not sure I'll have permission for this: @bors retry

2023-05-05 09:11 UTC, JohnTitor commented
@bors retry

2023-05-06 02:18 UTC, JohnTitor commented
@bors retry

2023-05-06 04:21 UTC, merged