Update crate version to 0.2.144
rust-lang/libc pull request #3239
Opened 2023-05-07 09:29 UTC by GuillaumeGomez

Please make a new release so I can use the new constants I added for macOS. :)

r? @Amanieu

2023-05-07 11:00 UTC, Amanieu commented
r? @JohnTitor

2023-05-07 13:34 UTC, JohnTitor requested changes
Could you also update the libc-test crate following the [contributing guide](https://github.com/rust-lang/libc/blob/master/CONTRIBUTING.md#releasing-your-change-to-cratesio)?

2023-05-07 14:07 UTC, GuillaumeGomez commented
Sorry, I keep forgetting about that. Updated.

2023-05-08 08:58 UTC, heiher reviewed
I remember changing the version number in three places in [the last release](https://github.com/rust-lang/libc/pull/3236/files). :smiley:

2023-05-08 09:41 UTC, JohnTitor commented
Yeah, sorry that I wasn't clear, but could you also update the libc dependency version of the libc-test crate?

2023-05-08 11:04 UTC, GuillaumeGomez commented
Sorry, I should just have grepped on the current version number to see where I needed to update it... Updated! Thanks to both of you!

2023-05-08 11:06 UTC, JohnTitor approved these changes

2023-05-08 11:06 UTC, JohnTitor commented
Thank you too! @bors r+

2023-05-08 12:11 UTC, merged

2023-05-08 12:23 UTC, GuillaumeGomez commented
Thanks!