feat: closefrom() and close_range() for FreeBSD
rust-lang/libc pull request #3374
Opened 2023-10-06 09:55 UTC by SteveLauC

This PR

1. add `closefrom()` for all the FreeBSD versions since this is available since FreeBSD 8.0
2. add `close_range()` for FreeBSD 13/14
    
    `close_range()` seems to be available since FreeBSD 12.2, so I am not sure what we should do about FreeBSD 12 here :<

Ref:

* [Man page for `closefrom()` on FreeBSD 11](https://man.freebsd.org/cgi/man.cgi?query=closefrom&apropos=0&sektion=2&manpath=FreeBSD+11.4-RELEASE+and+Ports&arch=default&format=html)
* [Man page for `close_range()` on FreeBSD 12.2 RELEASE](https://man.freebsd.org/cgi/man.cgi?query=close_range&apropos=0&sektion=2&manpath=FreeBSD+12.2-RELEASE&arch=default&format=html)

2023-10-06 15:09 UTC, asomers requested changes
You should move `close_range` into freebsd/mod.rs  .  Even though it wasn't present in FreeBSD 11 and 12, that's fine.  The version-specific files should only be used for functions whose signature _changed_, not functions that got added.  For example, everything relating to 64-bit inodes.

2023-10-07 10:07 UTC, SteveLauC commented
> You should move `close_range` into freebsd/mod.rs . Even though it wasn't present in FreeBSD 11 and 12, that's fine. The version-specific files should only be used for functions whose signature _changed_, not functions that got added. For example, everything relating to 64-bit inodes.

Done! Thanks for the review!

2023-10-07 10:34 UTC, JohnTitor approved these changes

2023-10-07 10:34 UTC, JohnTitor commented
@bors r+
Thank you both!

2023-10-07 11:36 UTC, merged