adding ifreq struct for openbsd
rust-lang/libc pull request #3384
Opened 2023-10-12 19:59 UTC by devnexen

2023-10-13 06:31 UTC, semarie requested changes
I don't have lot of time for reviewing now. I really hope you NEED it, and it isn't just because you see it is missing.

2023-10-13 06:31 UTC, semarie commented on src/unix/bsd/netbsdlike/openbsd/mod.rs
> +    }
in not `libc_union` case, the struct size is wrong and could lead to have `ioctl(2)` write outside the struct.

2023-10-14 03:09 UTC, JohnTitor approved these changes
Hope you need it, too...

2023-10-14 03:09 UTC, JohnTitor commented
@bors r+

2023-10-14 04:30 UTC, merged

2023-10-14 09:23 UTC, semarie reviewed
even if it is already merged, could you adress the two remarks please ?

2023-10-14 09:23 UTC, semarie commented on libc-test/build.rs
> +    cfg.skip_type(move |ty| {
this code seems not required (it built fine without it)

2023-10-17 06:33 UTC, semarie commented
@devnexen ping

2023-10-17 08:15 UTC, devnexen commented
sorry I missed that will look into in few hours. cheers.