strftime* api for *BSD
rust-lang/libc pull request #3483
Opened 2023-12-16 06:27 UTC by devnexen

close #3459

2023-12-16 08:13 UTC, semarie requested changes
just one nit on `semver/openbsd.txt`, else LGTM once corrected

2023-12-16 08:13 UTC, semarie commented on libc-test/semver/openbsd.txt
>  strncasecmp
symbols are added twice in openbsd

2023-12-17 02:58 UTC, JohnTitor approved these changes

2023-12-17 02:58 UTC, JohnTitor commented
@bors r+

2023-12-17 03:45 UTC, merged