Add in the sigtrap si_codes
rust-lang/libc pull request #4225
Opened 2024-12-31 16:18 UTC by xd009642

# Description

Adds the sigtrap si code constants for interpretting the results when getting siginfo after a sigtrap.

# Sources

I didn't include the perf trap as it's not on my system. 

https://github.com/torvalds/linux/blob/master/include/uapi/asm-generic/siginfo.h#L255-L264

# Checklist

- [x] Relevant tests in `libc-test/semver` have been updated
- [x] No placeholder or unstable values like `*LAST` or `*MAX` are
  included (see [#3131](https://github.com/rust-lang/libc/issues/3131))
- [x] Tested locally (`cd libc-test && cargo test --target mytarget`);
  especially relevant for platforms that may not be checked in CI

2025-01-10 08:53 UTC, tgross35 requested changes
Changes here lgtm, but you may as well also add `SI_DETHREAD`, `SI_ASYNCNL`, and `TRAP_PERF` so so the lists are complete. If this causes CI to fail on platforms with older headers, you should just be able to just skip them on 
https://github.com/rust-lang/libc/blob/55d8d8359ecdfacc1ce1d5a74c29ffd5586b454e/libc-test/build.rs.

Also - `linux_like/mod.rs` makes these available on both Android and emscripten (cc @maurer and @hoodmane). Android seems to have these https://cs.android.com/android/platform/superproject/main/+/main:bionic/libc/kernel/uapi/asm-generic/siginfo.h;l=118-127;drc=0f795217061c52c557fce451bf1c26ac578d1cbd but I don't think emscripten does, so these should probably be moved to `linux_like/linux.rs` and copied to `linux_like/linux/mod.rs` and copied to `linux_like/android/mod.rs`. (I want to organize this crate at some point so less of this is needed).

2025-01-10 09:34 UTC, hoodmane commented
These are all present in Emscripten. For instance:
```C
#include <signal.h>

_Static_assert(SI_ASYNCIO == -4);
```
compiles fine. So I think it is fine to include them in Emscripten. Whether they are useful for anything is a separate question.

2025-01-10 10:08 UTC, tgross35 commented
I stand corrected, thanks for checking so quickly!

In that case @xd009642 if you could add the remaining few constants then this should be good to merge.

2025-01-10 10:11 UTC, xd009642 commented
Sure it'll have to wait till Monday at the earliest as I'm on holiday but will do 🫡

2025-01-13 16:42 UTC, xd009642 commented
@tgross35 okay I'm hoping it's all good, looks like that last android test should pass as well.

2025-01-27 06:42 UTC, xd009642 commented
Just a bump to see what I should do about the Android failure?

2025-01-27 08:04 UTC, tgross35 commented
I'll just retry it, sometimes that job fails without any reason.

2025-01-27 08:04 UTC, tgross35 commented
Fyi also, everything is blocked until https://github.com/rust-lang/libc/pull/4254 merges, plus one upstream rust-lang/rust PR.

2025-01-27 08:08 UTC, tgross35 approved these changes
Assuming there aren't any other failures, this LGTM. Could you please squash once CI looks good?

2025-01-27 08:15 UTC, xd009642 commented
Sure, android failed again but I squashed anyway. I guess I'll potentially have to rebase etc once that other PR is merged

2025-01-27 08:17 UTC, tgross35 commented
I think it failed for a different reason now :) I guess give it a couple days for the r-l/rust PR and then the `libc` PR to merge, then I'll try it again.

2025-02-06 07:16 UTC, xd009642 commented
@tgross35 all the tests passed after merging in the changes from master so I've just squashed it into a single commit. Let me know if there's anything else that needs doing :smile:

2025-02-06 07:52 UTC, merged